feat: tweaks

diff --git a/tests/spread/lib/install-slices b/tests/spread/lib/install-slices
--- a/tests/spread/lib/install-slices
+++ b/tests/spread/lib/install-slices
@@ -1,4 +1,4 @@
-#!/bin/bash -ex
+#!/bin/bash -e
 # spellchecker: ignore rootfs
 
 # Installs one or more slices into a dynamically created temporary path.
@@ -50,25 +50,30 @@ function chisel_cut() {
     local n_retries=3
     local attempt
 
+    local output=$(mktemp)
     for ((attempt=1; attempt<=n_retries; attempt++)); do
         #shellcheck disable=SC2086
-        local output=$(chisel cut --ignore=unstable --release "$PROJECT_PATH" --root "$rootfs" $slices 2>&1)
-        local ret=$?
-        [ $ret -eq 0 ] && break
+        chisel cut \
+            --ignore=unstable \
+            --release "$PROJECT_PATH" \
+            --root "$rootfs" \
+            $slices \
+            2>&1 | tee "$output"
+        [[ "${PIPESTATUS[0]}" -eq 0 ]] && break
 
         local matched=""
         for pattern in "${_PATTERNS_TO_RETRY[@]}"; do
-            if [[ "$output" == *"$pattern"* ]]; then
+            if grep -q "$pattern" "$output"; then
                 matched="$pattern"
                 break
             fi
         done
 
         if [ $attempt -lt $n_retries ] && [ -n "$matched" ]; then
-            echo "Warning: Error while installing $slices (attempt $attempt/$n_retries): $matched. Retrying..." >&2
+            echo "Warning: Error while installing $slices (attempt $attempt/$n_retries). Retrying..." >&2
             continue
         else
-            echo "Failed to cut slices: $output" >&2
+            echo "Failed to cut slices: $(cat "$output")" >&2
             exit 1
         fi
     done
